enyo.depends(
	"AudioPlayback.css",
	"AudioPlaybackSample.css",
	"Music.TrackOneColumnWideSample.css",
	"Sound.js",
	"FullScreenDrawer.js",
	"AudioPlaybackSlider.js",
	"Music.TrackOneColumnWideSample.js",
	"AudioPlayback.js",
	"AudioPlaybackSample.js"
);
