enyo.depends(
	"Button.js",
	"Checkbox.js",
	"ExpandableInput.js",
	"IconButton.js",
	"Input.js",
	"InputDecorator.js",
	"Popup.js",
	"PopupPanel.js",
	"ProgressBar.js",
	"Slider.js",
	"CardOverlayArranger.js",
	"ToggleButton.js",
	"InputHeader.js",
	"TimePicker.js",
	"TooltipDecorator.js",
	"Tooltip.js",
	"Spinner.js"
);
