enyo.depends(
	"Button.js",
	"Checkbox.js",
	"ExpandableInput.js",
	"IconButton.js",
	"Input.js",
	"InputDecorator.js",
	"Popup.js",
	"ProgressBar.js",
	"Slider.js",
	"CardOverlayArranger.js",
	"ToggleButton.js"
);