enyo.depends(
	"Button.js",
	"Item.js",
	"Panels.js",
	"SimplePicker.js",
	"Checkbox.js",
	"LabeledCheckbox.js",
	"Toggle.js",
	"LabeledToggle.js",
	"RadioButton.js",
	"Drawer.js",
	"ExpandableList.js",
	"ExpandablePicker.js"
);